
package vista;

import controlador.Oyente;
import javax.swing.JComboBox;


/**
 *
 * @author Mui_f
 */
public class PanelDatos extends javax.swing.JPanel {

    
    /**
     * Creates new form PanelDatos
     */
    public PanelDatos() {
        initComponents();
    }
    
    public void agregarOyente(Oyente oyente){
        botonConsultar.addActionListener(oyente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelTabla = new javax.swing.JLabel();
        separadorUsuario = new javax.swing.JSeparator();
        labelEsquina = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelFotoP = new javax.swing.JLabel();
        comboTabla = new javax.swing.JComboBox<>();
        labelSubtitulo = new javax.swing.JLabel();
        botonConsultar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTitulo.setText("Bienvenido a Banco A3M");
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 280, 50));

        labelTabla.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        labelTabla.setText("Tabla:");
        add(labelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        separadorUsuario.setForeground(new java.awt.Color(153, 153, 153));
        separadorUsuario.setAutoscrolls(true);
        add(separadorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 310, 20));

        labelEsquina.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        labelEsquina.setText("Banco A3M");
        add(labelEsquina, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelFotoP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fotoPrincipal.jpg"))); // NOI18N
        labelFotoP.setText("jLabel2");
        jPanel1.add(labelFotoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 450));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 430));

        comboTabla.setFont(new java.awt.Font("Sitka Subheading", 0, 18)); // NOI18N
        comboTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Pagaré", "Amortización", "Tasa" }));
        add(comboTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 190, -1));

        labelSubtitulo.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        labelSubtitulo.setText("Seleccione la opción que necesite");
        add(labelSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        botonConsultar.setBackground(new java.awt.Color(204, 204, 255));
        botonConsultar.setFont(new java.awt.Font("Sitka Heading", 0, 14)); // NOI18N
        botonConsultar.setText("Consultar");
        add(botonConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 100, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultar;
    private javax.swing.JComboBox<String> comboTabla;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelEsquina;
    private javax.swing.JLabel labelFotoP;
    private javax.swing.JLabel labelSubtitulo;
    private javax.swing.JLabel labelTabla;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JSeparator separadorUsuario;
    // End of variables declaration//GEN-END:variables

public JComboBox getCombo(){
    return comboTabla;
}


}
